controllers/UserController.php
<?php

/*****************************************************************************************
 * EduSec  Open Source Edition is a School / College management system developed by
 * RUDRA SOFTECH. Copyright (C) 2010-2015 RUDRA SOFTECH.

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses. 

 * You can contact RUDRA SOFTECH, 1st floor Geeta Ceramics, 
 * Opp. Thakkarnagar BRTS station, Ahmedbad - 382350, India or
 * at email address info@rudrasoftech.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * RUDRA SOFTECH" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by RUDRA SOFTECH".
*****************************************************************************************/

/**
 * UserController implements the CRUD actions for User model.
 */

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\student\models\StuMasterSearch;
use app\modules\student\models\StuMaster;
use app\modules\student\models\StuInfo;
use app\modules\employee\models\EmpMasterSearch;
use app\modules\employee\models\EmpMaster;
use app\modules\employee\models\EmpInfo;

class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionChange()
    {
	$model=$this->findModel(Yii::$app->user->id);
	$model->scenario = 'change';

	if(isset($_POST['User']))
	{
		$model->attributes = $_POST['User'];
		$user = User::findOne(Yii::$app->user->id);
		$model->user_password = md5($model->new_pass.$model->new_pass);
		if($model->save())
			return $this->redirect(['/site/index']);
	}

	return $this->render('password_changeform',[
		'model'=>$model,
	]);
     }

    public function actionResetstudpassword()
    {
	$model = new StuMasterSearch();

	return $this->render('resetstudpassword',[
		'model'=>$model,
	]);
    }
   
    public function actionUpdateStudPassword($id)
    {
		$model=$this->findModel($id);
		$student_data = StuMaster::find()->where(['stu_master_user_id'=>$_REQUEST['id']])->one();
		$student_info = StuInfo::findOne($student_data->stu_master_stu_info_id)->stu_first_name;
		$model->user_password=MD5($model->user_login_id.$model->user_login_id);
		$model->updated_by = Yii::$app->getid->getId();
		$model->updated_at= new \yii\db\Expression('NOW()');
		if($model->save()) {
		 	\Yii::$app->session->setFlash('resetstudpassword',"<i class='glyphicon glyphicon-info-sign'></i> ".$student_info."'s Password is Reset");
			return $this->redirect(['user/resetstudpassword']);
		}
		
     }

     public function actionResetemppassword()
     {
	$model=new EmpMasterSearch();

	return $this->render('resetemppassword',[
			'model'=>$model,
		]);
     }

     public function actionUpdateEmpPassword($id)
     { 
		$model=$this->findModel($id);
		$emp_data = EmpMaster::find()->where(['emp_master_user_id'=>$id])->one();		
		$emp_info = EmpInfo::findOne($emp_data->emp_master_emp_info_id)->emp_first_name;
		$model->user_password=MD5($model->user_login_id.$model->user_login_id);
		$model->updated_by = Yii::$app->getid->getId();
		$model->updated_at= new \yii\db\Expression('NOW()');
		if($model->save()) {
		 	\Yii::$app->session->setFlash('resetemppassword',"<i class='glyphicon glyphicon-info-sign'></i> " .$emp_info."'s Password is Reset");
			return $this->redirect(['user/resetemppassword']);
		}
		
    }

    public function actionResetemploginid()
    {
	$model = new EmpMasterSearch();
	
	return $this->render('resetemploginid',[
		'model'=>$model,
	]);
    }

    /** Use for update employee login user details.
	*  @param integer $id the ID of the model to be update.
	*/
    public function actionUpdateemploginid($id)
    {
	$model=$this->findModel($id);
	$emp_data = EmpMaster::find()->where(['emp_master_user_id'=>$id])->one();		
	$emp_info = EmpInfo::findOne($emp_data->emp_master_emp_info_id)->emp_first_name;

	if(isset($_POST['User']))
	{
		$model->attributes=$_POST['User'];
		$model->user_login_id = $_POST['User']['user_login_id'];
		\Yii::$app->session->setFlash('resetemploginid',"<i class='glyphicon glyphicon-info-sign'></i> " .$emp_info."'s Login id is Reset");

		if($model->save()) {
			\Yii::$app->session->setFlash('resetemploginid',"<i class='glyphicon glyphicon-info-sign'></i> " .$emp_info."'s Login id is Reset");
			return $this->redirect(['resetemploginid']);
		}
	}

	return $this->render('updateemploginid',[
		'model'=>$model,
	]);
    }

    public function actionResetstudloginid()
    {
	$searchModel = new StuMasterSearch();
	$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

	return $this->render('resetstudloginid',[
		'searchModel'=>$searchModel,'dataProvider' => $dataProvider,
	]);
    }

    public function actionUpdatestudloginid($id)
    {
	$model=$this->findModel($id);
	$student_data = StuMaster::find()->where(['stu_master_user_id'=>$_REQUEST['id']])->one();
	$student_info = StuInfo::findOne($student_data->stu_master_stu_info_id)->stu_first_name;

	if(isset($_POST['User']))
	{
		$model->attributes=$_POST['User'];
		$model->user_login_id = $_POST['User']['user_login_id'];
		\Yii::$app->session->setFlash('resetstudloginid',"<i class='glyphicon glyphicon-info-sign'></i> " .$student_info."'s Login id is Reset");
		if($model->save()) {
			\Yii::$app->session->setFlash('resetstudloginid',"<i class='glyphicon glyphicon-info-sign'></i> " .$student_info."'s Login id is Reset");
			return $this->redirect(['resetstudloginid']);
		}
	}

	return $this->render('updatestudloginid',[
		'model'=>$model,
	]);
    }
    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/resetemploginid.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\modules\student\models\StudentDocsTrans */

$this->title = Yii::t('app', 'Reset Employee Login');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Employee'), 'url'=>['/employee']];
$this->params['breadcrumbs'][] = $this->title;
?>
  
<?php if(\Yii::$app->session->hasFlash('resetemploginid')) : ?>
<div class="col-xs-12" style="padding-top: 20px">
   <div class="alert alert-success alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
	<?php echo \Yii::$app->session->getFlash('resetemploginid'); ?>
   </div>
</div>
<?php endif; ?>

<?php $dataProvider = $model->search(Yii::$app->request->queryParams); ?>

<div class="col-xs-12">
  <div class="col-lg-12 col-sm-12 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-th-list"></i> <?= $this->title ?></h3></div>
</div>


<div class="col-xs-12">
<div class="box">
      <div class="box-body">
	<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $model,
	'summary'=> '' ,
	'options' => ['class' => 'table-responsive'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
		
		[
			'label' => Yii::t('emp', 'Employee ID'),
			'attribute' => 'emp_unique_id',
			'value' => 'empMasterEmpInfo.emp_unique_id',
 	        ],
		[
			'label' => Yii::t('emp', 'First Name'),
			'attribute' => 'emp_first_name',
			'value' => 'empMasterEmpInfo.emp_first_name',
 	        ],
		[
			'label' => Yii::t('emp', 'Last Name'),
			'attribute' => 'emp_last_name',
			'value' => 'empMasterEmpInfo.emp_last_name',
 	        ],
		[
			'label' => Yii::t('emp', 'Department'),
			'attribute' => 'emp_master_department_id',
			'value' => 'empMasterDepartment.emp_department_name',
			'filter' =>ArrayHelper::map(app\modules\employee\models\EmpDepartment::find()->all(),'emp_department_id','emp_department_name')
                ],
		[
			'label' => Yii::t('emp', 'Designation'),
			'attribute' => 'emp_master_designation_id',
			'value' => 'empMasterDesignation.emp_designation_name',
			'filter' => ArrayHelper::map(app\modules\employee\models\EmpDesignation::find()->all(),'emp_designation_id','emp_designation_name')
                ],
		[
		      'label' => Yii::t('app', 'User Login Id'),
		      'attribute' => 'user_login_id',
	              'value' => 'empMasterUser.user_login_id',
		      'options'=>['style'=>'min-width:140px'],
                ],
                [
		'class' => 'yii\grid\ActionColumn',
		'template' => '{Reset_password}',
		'buttons' => [
			    'Reset_password' => function ($url, $model) {
				return Html::a('<span class="glyphicon glyphicon-edit"></span>', $url, [
					    'title' => Yii::t('app', 'Reset Login'),
				]);
			    }
			],
			'urlCreator' => function ($action, $model, $key, $index) {
			    if ($action === 'Reset_password') {
				$url = \Yii::$app->getUrlManager()->createUrl(["user/updateemploginid", 'id' => $model->empMasterUser->user_id]);
				return $url;
			    }
			}	
	        ],
        ],
    ]); ?>
	</div>
   </div>
</div>

views/user/resetemppassword.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model app\modules\student\models\StudentDocsTrans */

$this->title = Yii::t('app', 'Reset Employee Password');

$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Employee'), 'url'=>['/employee']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Reset Employee Password')];
?>

<?php if(\Yii::$app->session->hasFlash('resetemppassword')) : ?>
<div class="col-xs-12" style="padding-top: 20px">
   <div class="alert alert-success alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
	<?php echo \Yii::$app->session->getFlash('resetemppassword'); ?>
   </div>
</div>
<?php endif;  ?>

<?php $dataProvider = $model->search(Yii::$app->request->queryParams); ?>
<div class="col-xs-12">
  <div class="col-lg-12 col-sm-12 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-th-list"></i> <?= $this->title ?></h3></div>
</div>


<div class="col-xs-12" style="padding-top: 10px;">
   <div class="box">
      <div class="box-body">
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $model,
	'summary' => '',
	'options' => ['class' => 'table-responsive'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
		
		[
			'label' => Yii::t('emp', 'Employee ID'),
			'attribute' => 'emp_unique_id',
			'value' => 'empMasterEmpInfo.emp_unique_id',
 	        ],
		[
			'label' => Yii::t('emp', 'First Name'),
			'attribute' => 'emp_first_name',
			'value' => 'empMasterEmpInfo.emp_first_name',
 	        ],
		[
			'label' => Yii::t('emp', 'Last Name'),
			'attribute' => 'emp_last_name',
			'value' => 'empMasterEmpInfo.emp_last_name',
 	        ],
		[
			'label' => Yii::t('emp', 'Department'),
			'attribute' => 'emp_master_department_id',
			'value' => 'empMasterDepartment.emp_department_name',
			'filter' =>ArrayHelper::map(app\modules\employee\models\EmpDepartment::find()->all(),'emp_department_id','emp_department_name')
                ],
		[
			'label' => Yii::t('emp', 'Designation'),
			'attribute' => 'emp_master_designation_id',
			'value' => 'empMasterDesignation.emp_designation_name',
			'filter' => ArrayHelper::map(app\modules\employee\models\EmpDesignation::find()->all(),'emp_designation_id','emp_designation_name')
                ],
		[
		      'label' => Yii::t('app', 'User Login Id'),
		      'attribute' => 'user_login_id',
	              'value' => 'empMasterUser.user_login_id',
		      'options'=>['style'=>'min-width:140px'],
		      
                ],
            [
		'class' => 'yii\grid\ActionColumn',
		'template' => '{Reset_password}',
		'buttons' => [
			    'Reset_password' => function ($url, $model) {
				return Html::a('<span class="glyphicon glyphicon-lock" style="font-size:20px"></span>', $url, [
					    'title' => Yii::t('app', 'Reset Password'),
				]);
			    }
			],
		'urlCreator' => function ($action, $model, $key, $index) {
			    if ($action === 'Reset_password') {
				$url = \Yii::$app->getUrlManager()->createUrl(["user/update-emp-password", 'id' => $model->empMasterUser->user_id]);
				return $url;
			    }
			}	
	    ],
        ],
    ]); ?>
    </div>
</div>
</div>

views/user/resetstudloginid.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\modules\student\models\StudentDocsTrans */

$this->title = Yii::t('app', 'Reset Student Login');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Student'), 'url'=>['/student']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php if(\Yii::$app->session->hasFlash('resetstudloginid')) 
      {
?>
<div class="col-xs-12" style="padding-top: 20px">
    <div class="alert alert-success alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<?php echo \Yii::$app->session->getFlash('resetstudloginid'); ?>
    </div>
</div>
<?php
      }
?>
<div class="col-xs-12">
  <div class="col-lg-12 col-sm-12 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-th-list"></i> <?= $this->title ?></h3></div>
</div>

<div class="col-xs-12" style="padding-top: 10px;">
   <div class="box">
      <div class="box-body">
	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'summary'=>'',
		'options' => ['class' => 'table-responsive'],
		'columns' => [
		    ['class' => 'yii\grid\SerialColumn'],
		
			[
			'label' => Yii::t('stu', 'Student ID'),
			'attribute' => 'stu_unique_id',
			'value' => 'stuMasterStuInfo.stu_unique_id',
	 	    ],
	
		    [
			'label' => Yii::t('stu', 'First Name'),
			'attribute' => 'stu_first_name',
			'value' => 'stuMasterStuInfo.stu_first_name',
	 	    ],
		    [
			'label' => Yii::t('stu', 'Last Name'),
			'attribute' => 'stu_last_name',
			'value' => 'stuMasterStuInfo.stu_last_name',
	 	    ],

		    [
			'label' => Yii::t('course', 'Course'),
			'attribute' => 'stu_master_course_id',
			'value' => 'stuMasterCourse.course_name',
			'filter' => ArrayHelper::map(app\modules\course\models\Courses::find()->where(['is_status' => 0])->all(), 'course_id', 'course_name')
		    ],
	    
		    [
			'label' => Yii::t('course', 'Batch'),
			'attribute' => 'stu_master_batch_id',
			'value' => 'stuMasterBatch.batch_name',
			'filter' => ArrayHelper::map(app\modules\course\models\Batches::find()->where(['is_status' => 0])->all(), 'batch_id', 'batch_name', 'batchCourse.course_name')
		    ],
	 
		    [
			      'label' => Yii::t('app', 'User Login Id'),
			      'attribute' => 'user_login_id',
			      'value' => 'stuMasterUser.user_login_id',
		    ],
		    [
			'class' => 'yii\grid\ActionColumn',
			'template' => '{Reset_loginid}',
			'buttons' => [
				    'Reset_loginid' => function ($url, $model) {
					return Html::a('<span class="glyphicon glyphicon-edit"></span>', $url, [
						    'title' => Yii::t('app', 'Reset Login'),
					]);
				    }
				],
			'urlCreator' => function ($action, $model, $key, $index) {
				    if ($action === 'Reset_loginid') {
					$url = \Yii::$app->getUrlManager()->createUrl(["user/updatestudloginid", 'id' => $model->stuMasterUser->user_id]);
					return $url;
				    }
				}	
		    ],
		],
	    ]); ?>
      </div>
    </div>
</div>

views/user/resetstudpassword.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model app\modules\student\models\StudentDocsTrans */

$this->title = Yii::t('app', Yii::t('app', 'Reset Student Password'));
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Student'), 'url'=>['/student']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Reset Student Password')];
?>
<?php if(\Yii::$app->session->hasFlash('resetstudpassword')) 
      {
?>
<div class="col-xs-12" style="padding-top: 20px">
    <div class="alert alert-success alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<?php echo \Yii::$app->session->getFlash('resetstudpassword'); ?>
    </div>
</div>
<?php
      } 
$dataProvider = $model->search(Yii::$app->request->queryParams);
?>
<div class="col-xs-12">
  <div class="col-lg-12 col-sm-12 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-th-list"></i> <?= $this->title ?></h3></div>
</div>

<div class="col-xs-12" style="padding-top: 10px;">
   <div class="box">
      <div class="box-body table-responsive">
	<div class="stu-reset-password-index">
	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $model,
		'summary'=>'',
		'options' => ['class' => 'table-responsive table'],
		'columns' => [
		    ['class' => 'yii\grid\SerialColumn'],
		
		    [
			'label' => Yii::t('stu', 'Student ID'),
			'attribute' => 'stu_unique_id',
			'value' => 'stuMasterStuInfo.stu_unique_id',
	 	    ],
	
		    [
			'label' => Yii::t('stu', 'First Name'),
			'attribute' => 'stu_first_name',
			'value' => 'stuMasterStuInfo.stu_first_name',
	 	    ],
		    [
			'label' => Yii::t('stu', 'Last Name'),
			'attribute' => 'stu_last_name',
			'value' => 'stuMasterStuInfo.stu_last_name',
	 	    ],
		    [
			'label' => Yii::t('course', 'Course'),
			'attribute' => 'stu_master_course_id',
			'value' => 'stuMasterCourse.course_name',
			'filter' => ArrayHelper::map(app\modules\course\models\Courses::find()->all(), 'course_id', 'course_name')
		    ],
		    [
			'label' => Yii::t('course', 'Batch'),
			'attribute' => 'stu_master_batch_id',
			'value' => 'stuMasterBatch.batch_name',
			'filter' => ArrayHelper::map(app\modules\course\models\Batches::find()->all(), 'batch_id', 'batch_name')
		    ],
		    [
			      'label' => Yii::t('app', 'User Login Id'),
			      'attribute' => 'user_login_id',
			      'value' => 'stuMasterUser.user_login_id',
		        ],
		    [
			'class' => 'yii\grid\ActionColumn',
			'template' => '{Reset_loginid}',
			'buttons' => [
				    'Reset_loginid' => function ($url, $model) {
					return Html::a('<span class="glyphicon glyphicon-lock" style="font-size:20px"></span>', $url, [
						    'title' => Yii::t('app', 'Reset Password'),
					]);
				    }
				],
			'urlCreator' => function ($action, $model, $key, $index) {
				    if ($action === 'Reset_loginid') {
					$url = \Yii::$app->getUrlManager()->createUrl(["user/update-stud-password", 'id' => $model->stuMasterUser->user_id]);
					return $url;
				    }
				}	
		    ],
		],
	    ]); ?>
   	</div>
      </div>
    </div>
</div>

views/user/updateemploginid.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
?>
<?php
$this->title = Yii::t('app', 'Update Employee Login');

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-xs-12">
  <div class="col-lg-12 col-sm-12 col-xs-12 no-padding"><h3 class="box-title"><i class="fa fa-edit"></i> <?php echo Yii::t('app', 'Update Employee Login'); ?> </h3></div>
</div>
<div class="col-xs-12 col-lg-12">
  <div class="<?php echo $model->isNewRecord ? 'box-success' : 'box-info'; ?> box view-item col-xs-12 col-lg-12">
<div class="emp-updateloginid-form">
    <?php $form = ActiveForm::begin([
			'id' => 'emp-change-loginid-form',
			//'enableAjaxValidation' => true,
		]); ?>

	
	
		<?php echo $form->field($model,'user_login_id',['inputOptions'=>[ 'class'=>'form-control','placeholder'=>'Login Id']])->textInput()->label(false); ?>
	

   

<div class="form-group col-xs-12 col-sm-6 col-lg-4 no-padding edusecArLangCss">
	<div class="col-xs-6">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord  ? 'btn btn-block btn-success' : 'btn btn-block btn-info']) ?>
	</div>
	<div class="col-xs-6">
	<?= Html::a(Yii::t('app', 'Reset'), ['user/resetemploginid'], ['class' => 'btn btn-default btn-block']) ?>
	</div>
     </div>

    <?php ActiveForm::end(); ?>
    </div>
  </div>
</div>

views/user/updatestudloginid.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

$this->title = Yii::t('app', 'Update Student Login : ').$model->user_login_id;
?>

<div class="col-xs-12 col-sm-12">
  	<div class="col-lg-8 col-sm-8 col-xs-12 no-padding edusecArLangCss"><h3 class="box-title"><i class="fa fa-pencil-square"></i> <?= $this->title ?></h3></div>
	<div class="col-lg-4 col-sm-4 col-xs-12">
		<div class="col-sm-4 col-xs-4 edusecArLangHide">
		</div>
		<div class="col-sm-4 col-xs-4 edusecArLangHide">
		</div>
		<div class="col-sm-4 col-xs-4 no-padding" style="padding-top: 20px !important;">	
		<?= Html::a(Yii::t('app', 'Back'), ['resetstudloginid'], ['class' => 'btn btn-block btn-back']) ?>
		</div>
	</div>
</div>

<div class="col-xs-12 col-lg-12">
  <div class="<?php echo $model->isNewRecord ? 'box-success' : 'box-info'; ?> box view-item col-xs-12 col-lg-12">
    <div class="form">
	<?php $form = ActiveForm::begin([
			'id' => 'stud-change-loginid-form',
			'fieldConfig' => [
			    'template' => "{label}{input}{error}",
			],
    ]); ?>

    <div class="col-xs-12 col-sm-12">
	<?= $form->field($model,'user_login_id')->textInput(); ?>
    </div>

    <div class="form-group col-xs-12 col-sm-6 col-lg-4 no-padding">
	<div class="col-xs-6">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord  ? 'btn btn-block btn-success' : 'btn btn-block btn-info']) ?>
	</div>
	<div class="col-xs-6">
	<?= Html::a(Yii::t('app', 'Cancel'), ['user/resetstudloginid'], ['class' => 'btn btn-default btn-block']) ?>
	</div>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
  </div>
</div>